import java.util.Map;
import java.util.HashMap;

public class Country
{
	private final String name;
	private Map neighbors = new HashMap<String, Country>();
	private MapColor color = null;
	
	public Country(String name)
	{
		this.name = name;
	}
	
	public string getName()
	{
		return name;
	}
	
	public MapColor getColor()
	{
		return color;
	}
	
	public void changeColor(MapColor newColor)
	{
		color = newColor;
	}
	
	/* Cost function for the country
	 * Generated by simply counting up the number of adjacent countries that 
	 * aren't colored yet
	 */
	public int getCost()
	{
		int cost = 0;
		for(Map.Entry<String, Country> countryEntry : neighbors.entrySet()) {
			if(countryEntry.getValue().getColor() == null) {
				cost += 1;
			
			} else {
			}
		}
		
		return cost;
	}
	
	public void addNeighbor(Country newNeighbor)
	{
		String key = newNeighbor.getName();
		if(!neighbors.containsKey(key)) {
			neighbors.put(key, newNeighbor());
		}
	}
}

























